export enum ActionTypeKeys {
  FETCH_RAMEN_INPROGRESS = 'FETCH_RAMEN_INPROGRESS',
  FETCH_RAMEN_SUCCESS = 'FETCH_RAMEN_SUCCESS',
  FETCH_RAMEN_FAIL = 'FETCH_RAMEN_FAIL',
  AUTH_USER_SET = 'AUTH_USER_SET',
  LOG_OUT = 'LOG_OUT',
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  SIGN_UP_ERROR = 'SIGN_UP_ERROR',
  SIGN_IN_ERROR = 'SIGN_IN_ERROR'
}