export enum ActionTypeKeys {
  FETCH_RAMEN_INPROGRESS = 'FETCH_RAMEN_INPROGRESS',
  FETCH_RAMEN_SUCCESS = 'FETCH_RAMEN_SUCCESS',
  FETCH_RAMEN_FAIL = 'FETCH_RAMEN_FAIL',
  AUTH_USER_SET = 'AUTH_USER_SET',
  LOG_OUT = 'LOG_OUT',
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  SIGN_UP_ERROR = 'SIGN_UP_ERROR',
  SIGN_IN_ERROR = 'SIGN_IN_ERROR',
  START_JOB = 'START_JOB',
  UPDATE_2FA = 'UPDATE_2FA',
  UPDATE_PROGRESS = 'UPDATE_PROGRESS',
  UPDATE_SCREENSHOT = 'UPDATE_SCREENSHOT',
  SEND_AUTH_MESSAGE = 'SEND_AUTH_MESSAGE',
  SUBMIT_AUTH_CODE = 'SUBMIT_AUTH_CODE'
}